esphome:
  name: roboeye-chatbot
  friendly_name: RoboEye-Chatbot
  platformio_options:
    lib_ldf_mode: chain+  
#  libraries:
#    - Improv=https://github.com/FluxGarage/RoboEyes.git
#    - adafruit/Adafruit SH110X
#    - adafruit/Adafruit GFX Library
#    - adafruit/Adafruit BusIO
#    - Wire
#    - SPI

esp32: 
  board: esp32-s3-devkitc1-n16r16

  framework: 
    type: arduino 

external_components:
  - source: 
      type: local
      path: external_components
    components: robo_eyes_wrapper
  
robo_eyes_wrapper:
  id: my_robo_eyes
  
button:
  - platform: template
    name: "Reset Eyes to Square"
    on_press:
      then:
        - robo_eyes.set_shape:
            id: my_robo_eyes
            width: 30
            height: 36
            radius: 10
            space: 10
            cyclops: false
  - platform: template
    name: "RoboEye: Close Eyes"
    icon: "mdi:eye-off"
    on_press:
      then:
        - robo_eyes.close:
            id: my_robo_eyes
  - platform: template
    name: "RoboEye: Open Eyes"
    icon: "mdi:eye"
    on_press:
      then:
        - robo_eyes.open:
            id: my_robo_eyes
  - platform: template
    name: "RoboEye Profile: Cyclops"
    on_press:
      then:
        - robo_eyes.set_shape:
            id: my_robo_eyes
            width: 40
            height: 40
            radius: 20
            cyclops: true
  - platform: template
    name: "RoboEye: Laugh"
    icon: "mdi:emoticon-laugh-outline"
    on_press:
      then:
        - robo_eyes.laugh:
            id: my_robo_eyes

  - platform: template
    name: "RoboEye: Confused"
    icon: "mdi:help-circle-outline"
    on_press:
      then:
        - robo_eyes.confused:
            id: my_robo_eyes


  

select:
  - platform: template
    name: "RoboEye Look Direction"
    id: eye_position_selector
    options:
      - "DEFAULT"
      - "N"
      - "NE"
      - "E"
      - "SE"
      - "S"
      - "SW"
      - "W"
      - "NW"
    initial_option: "DEFAULT"
    set_action:
      then:
        - robo_eyes.set_position:
            id: my_robo_eyes
            position: !lambda 'return x;'
  - platform: template
    name: "RoboEye Mood"
    id: eye_mood_selector
    options:
      - "DEFAULT"
      - "TIRED"
      - "ANGRY"
      - "HAPPY"
    initial_option: "DEFAULT"
    set_action:
      then:
        - robo_eyes.set_mood:
            id: my_robo_eyes
            mood: !lambda 'return x;'

switch:
  - platform: template
    name: "RoboEye Sweat Mode"
    id: eye_sweat_switch
    optimistic: true  # <--- Ensure this is set
    restore_mode: ALWAYS_OFF  # Do not try to restore previous state
    turn_on_action:
      then:
        - robo_eyes.set_sweat:
            id: my_robo_eyes
            state: true
    turn_off_action:
      then:
        - robo_eyes.set_sweat:
            id: my_robo_eyes
            state: false

  - platform: template
    name: "RoboEye Curiosity"
    id: eye_curiosity_switch
    optimistic: true  # <--- Ensure this is set
    turn_on_action:
      then:
        - robo_eyes.set_curiosity:
            id: my_robo_eyes
            state: true
    turn_off_action:
      then:
        - robo_eyes.set_curiosity:
            id: my_robo_eyes
            state: False
  - platform: template
    name: "RoboEye Auto-Wander (Idle Mode)"
    id: eye_idle_switch
    icon: "mdi:eye-sync"
    optimistic: true
    restore_mode: ALWAYS_ON # Start with eyes looking around
    turn_on_action:
      then:
        - robo_eyes.set_idle_mode:
            id: my_robo_eyes
            state: true
    turn_off_action:
      then:
        - robo_eyes.set_idle_mode:
            id: my_robo_eyes
            state: false

# Enable logging
logger:
  level: DEBUG # you can set to INFO, WARN, ERROR if you prefer less output

# Enable Home Assistant API
api:
  encryption:
    key: "5G/0qT+o5eapd/hRAWDFTkop4qWUjOiGJ4GDFePULPI="
  services:
    - service: robo_happy
      then:
        - robo_eyes.set_mood:
            id: my_robo_eyes
            mood: "HAPPY"  # Ensure mood is quoted as a string
    - service: robo_angry
      then:
        - robo_eyes.set_mood:
            id: my_robo_eyes
            mood: "ANGRY"
            
ota:
  - platform: esphome
    password: "c761330ac5c1b2277363df6da670368e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Roboeye-Chatbot Fallback Hotspot"
    password: "hEfuymBbD2kb"

captive_portal:

web_server:
  port: 80
